[general](#general)  
[recognition](#recognition)   
[install](#install)   
[1 recognize_google](#1-recognize_google)   
[2 recognize_sphinx](#2-recognize_sphinx)   
[3 Microphone](#3-Microphone)   
[закладки](#закладки)   
[2 mMakeMd](#2-mMakeMd)  
[mPrepbmla](#mPrepbmla)  
[yotube time](#yotube-time)  
[Path](#Path)   
[clipboard](#clipboard)   
[1 what in clipboard](#1-what-in-clipboard)   
[2 codecs](#2-codecs)   
[3 end](#3-end)   
[footer](#footer)   
[](#)  
[](#)  


## general

In [1]:
def mReadFile(fileName):
    s = ''
    with open(fileName, encoding="utf8") as file:
        s = file.read()
    return s

def mWriteFile(fileName, text):
    with open(fileName, "w", encoding="utf8") as file:
        file.write(text)
    

def mStrToList(s):
    l = s.split('\n')
    l2 = []
    for v in l:
        l2.append(v.strip())
        pass
    l2 = list(filter(lambda v: len(v.strip())>0, l2))
#     print('l2', l2)
    return l2
print('ok')



ok


## recognition

### install
```
pip install pipwin 
pipwin install pyaudio
pipwin install pocketsphinx
```

## 1 recognize_google

In [156]:
import speech_recognition as sr
print(sr.__version__)

3.8.1


In [157]:
import speech_recognition as sr

r = sr.Recognizer()
harvard = sr.AudioFile('harvard.wav')
with harvard as source:
    audio = r.record(source)
r.recognize_google(audio)    


'the stale smell of old beer lingers it takes heat to bring out the odor a cold dip restores health and zest a salt pickle taste fine with ham tacos al Pastore are my favorite a zestful food is be hot cross bun'

## 2 recognize_sphinx

In [158]:
import speech_recognition as sr

r = sr.Recognizer()
harvard = sr.AudioFile('harvard.wav')
with harvard as source:
    audio = r.record(source)
r.recognize_sphinx(audio)    


"this they'll smell of old we're lingers it takes heat to bring out the odor called it restores health and zest case all the colt is fine with him couples all pastore my favorite is as full food is the hot cross mon"

## 3 Microphone

In [159]:
import speech_recognition as sr  
   
# obtain audio from the microphone  
r = sr.Recognizer()  
with sr.Microphone() as source:  
    print("Say something!")  
    audio = r.listen(source)  

# recognize speech using Sphinx  
try:  
    print("Sphinx thinks you said '" + r.recognize_sphinx(audio) + "'")  
except sr.UnknownValueError:  
    print("Sphinx could not understand audio")  
except sr.RequestError as e:  
    print("Sphinx error; {0}".format(e))  

Say something!
Sphinx could not understand audio


In [160]:
import speech_recognition as sr

r = sr.Recognizer()
harvard = sr.AudioFile('2.wav')
with harvard as source:
    audio = r.record(source)
s = '11'
s = r.recognize_sphinx(audio)    
mWriteFile("x27c.txt", s)
print(len(s))

FileNotFoundError: [Errno 2] No such file or directory: '2.wav'

## закладки


## 1 mBookmarksFolder
- mBookmarksFolder(txt, word, lst)   
принимает hrome export bookmarks  
искомая папка с закладками (tmp02)  
добавляет список строк вида `[]()`  
[]()  


In [2]:
from bs4 import BeautifulSoup as bf

def mReadFile(fileName):
    s = ''
    with open(fileName, encoding="utf8") as file:
        s = file.read()
    return s


def mWriteFile(fileName, text):
    with open(fileName, "w", encoding="utf8") as file:
        file.write(text)
    


def mBookmarksFolder(txt, word, lst):
    soup = bf(txt, 'lxml')
    soup2 = soup.find(string=word)
    soup3 = soup2.find_parent().find_parent()
    soup4 = soup3.find_parent()
    soup5 = soup4.find_all(["dl","h3"])

    ll = []
    for tag in soup5:
        if tag.name == "h3":
            ll.append([tag.text])
        elif tag.name == "dl":
            la0 = tag.find_all("a")
            la2 = [[e.text, e['href']] for e in la0 if e is not None]
            ll[-1].append(la2)

    for e in ll:
        if e[0]==word:
            for e2 in e[1]:
                s2 = f"[{e2[0]}]({e2[1]})"
                lst.append(s2)
 
    
txt = mReadFile("x27a.txt")
word = "tmp02"
# word = "a2"
lst = []
mBookmarksFolder(txt, word, lst)
mWriteFile("x27b.txt", '   \n'.join(lst))
    
print(len(lst))


18


In [39]:
import random

x = random.randint(1,3)
x = random.choice([1,3])
print(x)

1


java  
Math.nextInt  


import java.util.Collections;
[...]
Collection.shuffle(elements);
element_answer = elements[0];


```
D:\mailCloud\prjother\089hosts\jnotebook\js
D:\mailCloud\prjother\089hosts\jnotebook\js\bookmarks_0610.html
```

## 2 mMakeMd
x27bmka x27bmkb  
from `[head](http..)` to  
```
[head1](#head1)
[head2](#head2)


## head1
[head1](http1)
## head1
[head2](http2)
```

In [4]:
import re

def mMakeMd(l1, l2, l11 = []):
    l1b = []
    k = 0
    for e in l1:
        e2 = []
        match = re.search('\[(.*)\]\((.*)\)', e)
#         match = re.search('\[.*\]\(.*\)', e)
        if match and len(match.groups()) > 1:
            e2.append(match[1])
            e3 = match[1].replace(' ', '-')
            e2.append(e3)
            e2.append(match[2])
            if len(l11)>k:
                e2.append(l11[k])
            else:
                e2.append('')
            l1b.append(e2)
            
        k += 1    
        pass
    l2b = []
    for e in l1b:
        e2 = []
        e2.append(f'[{e[0]}](#{e[1]})')
        e2.append(f'## {e[0]}')
        e2.append(f'[{e[0]}]({e[2]})')
        e2.append(e[3])
        l2b.append(e2)
        pass

    l2link = []
    k = 1
    for e in l2b:
        l2link.append(f'{k} {e[0]}')
        k +=1
        pass

    l2paragrahp = []
    for e in l2b:
        l2paragrahp.append(e[1])
        l2paragrahp.append(e[2])
        l2paragrahp.append(e[3])
        pass

    l2a = l2link + l2paragrahp
    
    for e in l2a:
        l2.append(e+"  ")
    
#     print(l2)
#     print(l2link)
#     print(l1b)
    pass

s = mReadFile('x27bmka.txt')
l1 = mStrToList(s)
l2 = []
s = mReadFile('x27bmla.txt')
l11 = mStrToList(s)
# print(l11[:])
mMakeMd(l1, l2, l11)
for e in l2:
#     print(e)
    pass
mWriteFile('x27bmkb.txt', '\n'.join(l2))
print(len(l1), len(l2))

18 72


```
in:
[1 1](12)  
[21](22)
[31](32)

out:
[1 1](#1-1)  
[21](#21)  
[31](#31)  
## 1 1  
[1 1](12)  
[b1201 - github](https://github.com/mlapinm/b04andr)  
## 21  
[21](22)  

```

## mPrepbmla

In [27]:

s = '''
l2012var
l2022
l2032
l2042
l2052
l2062
l2072
l2082
l2092
l2102
l2112
l2122
l2132
l2142
l2152
l2162
l2172
l2182
l2192
l2202
'''
sn = ['https://github.com/mlapinm/b03andr', ' - github']


In [28]:
l = mStrToList(s)
for e in l:
    print(f'[{e}{sn[1]}]({sn[0]})')
    
    pass


[l2012var - github](https://github.com/mlapinm/b03andr)
[l2022 - github](https://github.com/mlapinm/b03andr)
[l2032 - github](https://github.com/mlapinm/b03andr)
[l2042 - github](https://github.com/mlapinm/b03andr)
[l2052 - github](https://github.com/mlapinm/b03andr)
[l2062 - github](https://github.com/mlapinm/b03andr)
[l2072 - github](https://github.com/mlapinm/b03andr)
[l2082 - github](https://github.com/mlapinm/b03andr)
[l2092 - github](https://github.com/mlapinm/b03andr)
[l2102 - github](https://github.com/mlapinm/b03andr)
[l2112 - github](https://github.com/mlapinm/b03andr)
[l2122 - github](https://github.com/mlapinm/b03andr)
[l2132 - github](https://github.com/mlapinm/b03andr)
[l2142 - github](https://github.com/mlapinm/b03andr)
[l2152 - github](https://github.com/mlapinm/b03andr)
[l2162 - github](https://github.com/mlapinm/b03andr)
[l2172 - github](https://github.com/mlapinm/b03andr)
[l2182 - github](https://github.com/mlapinm/b03andr)
[l2192 - github](https://github.com/mlapinm

## yotube time

In [5]:
surl = 'https://www.youtube.com/watch?v=_8V5o2UHG0E'
stime = '&t=s'
s = '''
⌨️ (0:00:00) Data Visualization Course Overview
⌨️ (0:02:50) Why Visualize Data?
⌨️ (0:14:28) Inputs for Data Visualization: Data & Tasks
⌨️ (0:29:31) Intro to Javascript

⌨️ (1:57:35) Intro to HTML, CSS & SVG

⌨️ (2:31:56) Intro to D3.js - Let's Make a Face!

⌨️ (3:15:06) Making a Bar Chart with D3.js and SVG

⌨️ (3:44:02) Customizing Axes of a Bar Chart with D3.js

⌨️ (4:10:03) Making a Scatter Plot with D3.js

⌨️ (4:34:22) Making Line and Area Charts with D3.js

⌨️ (5:04:36) The General Update Pattern of D3.js

⌨️ (6:04:30) Marks & Channels in Data Visualization
⌨️ (6:28:43) Interaction with Unidirectional Data Flow using D3.js

⌨️ (6:45:13) Making a World Map with D3

⌨️ (7:02:43) Cheap Tricks for Interaction on a D3.js World Map

⌨️ (7:25:37) Blank Canvas

⌨️ (7:30:43) Building a Tree Visualization of World Countries with D3.js

⌨️ (8:04:48) Color and Size Legends with D3.js

⌨️ (8:33:27) Choropleth Map with D3.js

⌨️ (9:05:16) Interactive Filtering on a Choropleth Map

⌨️ (9:51:00) Using Color in Visualization
⌨️ (10:07:54) Scatter Plot with Menus

⌨️ (10:54:03) Circles on a Map

⌨️ (11:35:51) Line Chart with Multiple Lines

⌨️ (11:59:34) Melting and Munging Data with JavaScript

⌨️ (12:28:29) Selecting a Year on a Line Chart
'''

In [6]:
import re

def mListNum(s2, l):
    '''
    '0:01:02' => [0, 1, 2] 
    '''
    k = 0
    l2 = []
    while 1:
        k2 = s2.find(':', k)
        if k2<0:
            l2.append(s2[k:])
            break
        l2.append(s2[k:k2])
        k = k2 + 1
    while len(l2)<3:
        l2.insert(0, 0)
    for e in l2:
        l.append(int(e))
        

l = mStrToList(s)
# l = l[:2]
l2 = []
for e in l:
    match = re.search(r'^.*((\d:)?\d\d:\d\d)\) ', e)
    k = len(match.groups()) if match else -1
    if k>0:
        e2 = e.replace(match[0],'')
        e3 = match[1]
        lt = []
        mListNum(e3, lt)
        lt.reverse()
        m = 1
        e4 = 0
        for e in lt:
            e4 += e*m
            m *= 60
        e5 = f'[{e2}]({surl}{stime[:-1]}{e4}{stime[-1:]})  '
        l2.append(e5)

        
for x in l2:
    print(x)
    


[Data Visualization Course Overview](https://www.youtube.com/watch?v=_8V5o2UHG0E&t=0s)  
[Why Visualize Data?](https://www.youtube.com/watch?v=_8V5o2UHG0E&t=170s)  
[Inputs for Data Visualization: Data & Tasks](https://www.youtube.com/watch?v=_8V5o2UHG0E&t=868s)  
[Intro to Javascript](https://www.youtube.com/watch?v=_8V5o2UHG0E&t=1771s)  
[Intro to HTML, CSS & SVG](https://www.youtube.com/watch?v=_8V5o2UHG0E&t=3455s)  
[Intro to D3.js - Let's Make a Face!](https://www.youtube.com/watch?v=_8V5o2UHG0E&t=1916s)  
[Making a Bar Chart with D3.js and SVG](https://www.youtube.com/watch?v=_8V5o2UHG0E&t=906s)  
[Customizing Axes of a Bar Chart with D3.js](https://www.youtube.com/watch?v=_8V5o2UHG0E&t=2642s)  
[Making a Scatter Plot with D3.js](https://www.youtube.com/watch?v=_8V5o2UHG0E&t=603s)  
[Making Line and Area Charts with D3.js](https://www.youtube.com/watch?v=_8V5o2UHG0E&t=2062s)  
[The General Update Pattern of D3.js](https://www.youtube.com/watch?v=_8V5o2UHG0E&t=276s)  
[Marks & Cha

In [15]:
def mListNum(s2, l):
    '''
    '0:01:02' => [0, 1, 2] 
    '''
    k = 0
    l2 = []
    while 1:
        k2 = s2.find(':', k)
        if k2<0:
            l2.append(s2[k:])
            break
        l2.append(s2[k:k2])
        k = k2 + 1
    while len(l2)<3:
        l2.insert(0, 0)
    for e in l2:
        l.append(int(e))

s2 = '01:02'
l2 = []
mListNum(s2, l2)
print(l2)

[0, 1, 2]


## Path

In [1]:
s2 = '''
[English Speaking 02](b0424vip.md)  

'''


In [2]:
import re

def mPath(s2, s3):
    l = s2.split('\n')
    l2 = []
    for e in l:
        k = e.find('http')
        if k < 0:
            k = e.find('](#')
        s5 = ''
        if k<0:
            # если есть палка, то заменяется то что до палки и палка 
            s5 = re.sub(f'\]\((\w+\/)?', f']({s3}/', e)
        else:
            s5 = e
        pass
        l2.append(s5)
    s4 = '\n'.join(l2)
    return s4

s4 = mPath(s2,'htmla2present')
print(s4)


[English Speaking 02](htmla2present/b0424vip.md)  




## clipboard
[Module win32clipboard](http://timgolden.me.uk/pywin32-docs/win32clipboard.html)   
[CF_BITMAP 2](https://docs.microsoft.com/en-us/windows/win32/dataxchg/standard-clipboard-formats)  
[WIN32 API. БУФЕР ОБМЕНА](http://www.cyberguru.ru/programming/win32/win32-clipboard.html?showall=&start=26)


### 1 what in clipboard

In [1]:
from io import StringIO
import win32clipboard

format_name=''
win32clipboard.OpenClipboard()
count = win32clipboard.CountClipboardFormats()
l = []
e = -1
for i in range(count):
    if i == 0:
        e = win32clipboard.EnumClipboardFormats()
    else:
        e = win32clipboard.EnumClipboardFormats(e)
    print(e) 
    ff = win32clipboard.GetClipboardData(e)
    print(ff)
    pass
win32clipboard.CloseClipboard()


49431
b'Version:0.9\r\nStartHTML:0000000105\r\nEndHTML:0000000336\r\nStartFragment:0000000141\r\nEndFragment:0000000300\r\n<html>\r\n<body>\r\n<!--StartFragment--><a href="https://interzet.domru.ru/">\xd0\x94\xd0\x9e\xd0\x9c.RU \xe2\x80\x93 \xd0\xb8\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80\xd0\xbd\xd0\xb5\xd1\x82-\xd0\xbf\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xb9\xd0\xb4\xd0\xb5\xd1\x80 \xd0\xb2 \xd0\xa1\xd0\xb0\xd0\xbd\xd0\xba\xd1\x82-\xd0\x9f\xd0\xb5\xd1\x82\xd0\xb5\xd1\x80\xd0\xb1\xd1\x83\xd1\x80\xd0\xb3\xd0\xb5 | \xd0\x9e\xd1\x84\xd0\xb8\xd1\x86\xd0\xb8\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9 \xd1\x81\xd0\xb0\xd0\xb9\xd1\x82</a><!--EndFragment-->\r\n</body>\r\n</html>\x00'
49443
b'\x14\x04\x1e\x04\x1c\x04.\x00R\x00U\x00 \x00\x13  \x008\x04=\x04B\x045\x04@\x04=\x045\x04B\x04-\x00?\x04@\x04>\x042\x040\x049\x044\x045\x04@\x04 \x002\x04 \x00!\x040\x04=\x04:\x04B\x04-\x00\x1f\x045\x04B\x045\x04@\x041\x04C\x04@\x043\x045\x04 \x00|\x00 \x00\x1e\x04D\x048\x04F\x048\x040\x04;\x04L\x04=\x04K\x0

```
49432
b'Version:0.9\r\nStartHTML:0000000105\r\nEndHTML:0000000226\r\nStartFragment:0000000141\r\nEndFragment:0000000190\r\n<html>\r\n<body>\r\n<!--StartFragment--><a href="https://www.yandex.ru/">\xd0\xaf\xd0\xbd\xd0\xb4\xd0\xb5\xd0\xba\xd1\x81</a><!--EndFragment-->\r\n</body>\r\n</html>\x00'
49444
b'/\x04=\x044\x045\x04:\x04A\x04\n\x00h\x00t\x00t\x00p\x00s\x00:\x00/\x00/\x00w\x00w\x00w\x00.\x00y\x00a\x00n\x00d\x00e\x00x\x00.\x00r\x00u\x00/\x00\x00\x00'
13
https://www.yandex.ru/
49892
b'\x9c\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x16\x00\x00\x00https://www.yandex.ru/\x00\x00\x06\x00\x00\x00/\x04=\x044\x045\x04:\x04A\x04|\x05\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x0c\x00\x00\x00last_visited\x11\x00\x00\x0013202844721658648\x00\x00\x00\x14\x00\x00\x00last_visited_desktop\x11\x00\x00\x0013204217544035837\x00\x00\x00'
16
b'\t\x04\x00\x00'
1
b'https://www.yandex.ru/'
7
b'https://www.yandex.ru/'

```

### 2 codecs

In [ ]:
s2 = b"\xd0\xaf\xd0\xbd\xd0\xb4\xd0\xb5\xd0\xba\xd1\x81"
s3 = s2.decode("utf-8")
print(s3)
print(hex(49444))





### 3 end

In [2]:
import win32clipboard
from bs4 import BeautifulSoup as bf

e = ''
txt = ''
win32clipboard.OpenClipboard()
e = win32clipboard.EnumClipboardFormats()
txt = win32clipboard.GetClipboardData(e)
win32clipboard.CloseClipboard()
soup = bf(txt, 'lxml')
la2 = []
for tag in soup:
    la0 = tag.find_all("a")
    la2 = [[e.text, e['href']] for e in la0 if e is not None]
    
print(la2)  


[['ДОМ.RU – интернет-провайдер в Санкт-Петербурге | Официальный сайт', 'https://interzet.domru.ru/']]


[convertio](https://convertio.co/ru/mp4-wav/)  
[python - PyAudio не устанавливается - Stack Overflow на русском](https://ru.stackoverflow.com/questions/927657/pyaudio-%D0%BD%D0%B5-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%B0%D0%B2%D0%BB%D0%B8%D0%B2%D0%B0%D0%B5%D1%82%D1%81%D1%8F)
[Speech Recognition - распознавание речи | Учебник Python 3](https://learn4kid-python.firebaseapp.com/python_data_structure/python_speech_recognition/#%D0%BA%D0%B0%D0%BA-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-%D1%80%D0%B0%D1%81%D0%BF%D0%BE%D0%B7%D0%BD%D0%B0%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%80%D0%B5%D1%87%D0%B8)   
[edureka! - YouTube](https://www.youtube.com/user/edurekaIN?sub_confirmation=1)  
[Speech Recognition Using Python | Speech To Text Translation in Python | Python Training | Edureka - YouTube](https://www.youtube.com/watch?v=sHeJgKBaiAI)  
[Python Full Course - Learn Python in 12 Hours | Python Tutorial For Beginners | Edureka - YouTube](https://www.youtube.com/watch?v=WGJJIrtnfpk&list=PL9ooVrP1hQOHY-BeYrKHDrHKphsJOyRyu)  
[Real-time Speech to Text with DeepSpeech - Getting Started on Windows and Transcribe Microphone Free - YouTube](https://www.youtube.com/watch?v=c_0Q3T0XYTA)  
[Python Speech Recognition | Open Website By Speech | Google Speech - YouTube](https://www.youtube.com/watch?v=a98tTmBZU9k&list=PL1FgJUcJJ03teZuZVmQY0_JcOi1ukrBYx&index=2)  
[Окончательное руководство по распознаванию речи с Python | Guru](https://cyberguru.tech/%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5/%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5/%D0%BE%D0%BA%D0%BE%D0%BD%D1%87%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D1%80%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE-%D0%BF%D0%BE-%D1%80%D0%B0%D1%81%D0%BF%D0%BE%D0%B7)  

## footer
[BeautifulSoup – парсинг HTML в Python на примерах](https://python-scripts.com/beautifulsoup-html-parsing)  